### ISSUE TITLE
some more pseudo code might be useful

### ISSUE THREAD

**Issue by georgiaewhitney** [fac26/Laura-Derek-Project-2#18]
it was a little tricky to follow some parts, despite it being very clean - a few more comments would be useful in following the flow of the script.

**Comment by LL835** [comment]
Thank for pointing that out, Georgia! We'll look through and try to make it easier to follow.

**Comment by LL835** [comment]
Ok! We've added some extra comments to `index.js`. Hope it's a bit clearer but let us know if not.

**Comment by georgiaewhitney** [comment]
This is great! This is also a great learning tool to read through - thanks :)
